backend:
  name: github
  repo: joisak/gatsby-den-sote-fine

local-backend: true

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: menus
    label: Menus
    folder: content/menus
    create: true
    fields:
      - { name: name, label: Menu Title }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description }
      - label: Dishes
        name: dishes
        widget: list
        fields:
          - { label: Name of the dish, name: name, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Price, name: price, widget: string }
  - name: menu
    label: Menu
    files:
      - file: content/menu/menu.yml
        label: Menu
        name: menu
        fields:
          - label: Main menu
            name: main-menu
            widget: list
            fields:
              - { label: Name of the dish, name: name, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Price, name: price, widget: string }

  - name: navigation
    label: Navigation
    files:
      - file: content/settings/navigation.yml
        label: Navigation
        name: nav_items
        widget: list
        fields:
          - label: Header Navigation
            name: header-navigation
            widget: list
            fields:
              - { label: Link-title, name: link-title, widget: string }
              - { label: Path, name: link-path, widget: string }
